import SetUpTL from '@/components/ui/telegram/SetUpTL';
import Head from 'next/head';
import React from 'react'

const telgram = () => {
  return (
    <div>
      <Head>
        <title>PlanPro | Telegram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/asset/planpro-favicon.svg" />
      </Head>

      <main>
        {/* <TelegramIntegration/> */}
        {/* <TelegramFeatureSetup/> */}
        <SetUpTL />
      </main>

    </div>
  )
}

export default telgram;