[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "20"
NEXT_PUBLIC_API_URL = "https://planpro-dev.up.railway.app/api"
NEXT_PUBLIC_WS_URL = "https://planpro-dev.up.railway.app/ws"
NEXT_PUBLIC_WS_FALLBACK_URL = "wss://planpro-dev.up.railway.app/ws"
NEXT_PUBLIC_SOCKJS_URL = "https://planpro-dev.up.railway.app/ws"
NEXTAUTH_SECRET = "yp07B20A68ncgpoiwDqnhWjLHLQ68iUy64Nk0wR0RBw0="
GOOGLE_API_KEY = "AIzaSyBSIVn_HrlfJ-HnD1oQ9qhVhcnXT92OPQI"
NEXT_PUBLIC_PWD_ENCRYPTION_KEY = "mytestkeyasdddds"
