import TodosList from '@/components/ui/todos/TodosList';
import Head from 'next/head';
import React from 'react'

const todos = () => {
  return (
    <div>
      <Head>
        <title>PlanPro | Todos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/asset/planpro-favicon.svg" />
      </Head>

      <main>
        <TodosList />
      </main>

    </div>
  )
}

export default todos;