import Tasks from '@/components/ui/todos/Tasks';
import Head from 'next/head';
import React from 'react'

const todos = () => {
  return (
    <div>
      <Head>
        <title>PlanPro | Todos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Tasks/>
      </main>

    </div>
  )
}

export default todos;