import { format, addDays } from "date-fns"
import type { Reminder } from "./types"

// Sample data
// export const generateSampleReminders = (): Reminder[] => {
//   const now = new Date()

//   return [
//     {
//       id: "rem-001",
//       title: "Pay monthly bills",
//       description: "Pay electricity, water, and internet bills",
//       dueDate: format(addDays(now, 2), "yyyy-MM-dd"),
//       dueTime: "18:00",
//       category: "Finance",
//       priority: "High",
//       reminderStatus: "Active",
//       recurring: true,
//       recurrenceType: "Monthly",
//       starred: true,
//       createdAt: format(addDays(now, -5), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(now, "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["bills", "monthly", "finance"],
//     },
//     {
//       id: "rem-002",
//       title: "Doctor's appointment",
//       description: "Annual checkup with Dr. Smith",
//       dueDate: format(addDays(now, 7), "yyyy-MM-dd"),
//       dueTime: "10:30",
//       category: "Health",
//       priority: "Medium",
//       reminderStatus: "Active",
//       recurring: false,
//       recurrenceType: "None",
//       starred: false,
//       createdAt: format(addDays(now, -10), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(addDays(now, -10), "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["health", "doctor", "annual"],
//     },
//     {
//       id: "rem-003",
//       title: "Team meeting",
//       description: "Weekly team sync with product and design",
//       dueDate: format(addDays(now, 1), "yyyy-MM-dd"),
//       dueTime: "14:00",
//       category: "Work",
//       priority: "Medium",
//       reminderStatus: "Active",
//       recurring: true,
//       recurrenceType: "Weekly",
//       starred: false,
//       createdAt: format(addDays(now, -15), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(addDays(now, -2), "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["meeting", "team", "weekly"],
//     },
//     {
//       id: "rem-004",
//       title: "Gym session",
//       description: "Cardio and strength training",
//       dueDate: format(now, "yyyy-MM-dd"),
//       dueTime: "07:00",
//       category: "Health",
//       priority: "Low",
//       reminderStatus: "Completed",
//       recurring: true,
//       recurrenceType: "Daily",
//       starred: false,
//       createdAt: format(addDays(now, -30), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(now, "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["fitness", "health", "routine"],
//     },
//     {
//       id: "rem-005",
//       title: "Call mom",
//       description: "Weekly catch-up call",
//       dueDate: format(addDays(now, -1), "yyyy-MM-dd"),
//       dueTime: "19:00",
//       category: "Personal",
//       priority: "Medium",
//       reminderStatus: "Missed",
//       recurring: true,
//       recurrenceType: "Weekly",
//       starred: true,
//       createdAt: format(addDays(now, -20), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(addDays(now, -1), "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["family", "personal", "call"],
//     },
//     {
//       id: "rem-006",
//       title: "Project deadline",
//       description: "Submit final project deliverables",
//       dueDate: format(addDays(now, 14), "yyyy-MM-dd"),
//       dueTime: "17:00",
//       category: "Work",
//       priority: "Urgent",
//       reminderStatus: "Active",
//       recurring: false,
//       recurrenceType: "None",
//       starred: true,
//       createdAt: format(addDays(now, -45), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(addDays(now, -3), "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["project", "deadline", "important"],
//     },
//     {
//       id: "rem-007",
//       title: "Dinner reservation",
//       description: "Anniversary dinner at Le Bistro",
//       dueDate: format(addDays(now, 10), "yyyy-MM-dd"),
//       dueTime: "20:00",
//       category: "Social",
//       priority: "Medium",
//       reminderStatus: "Active",
//       recurring: false,
//       recurrenceType: "None",
//       starred: false,
//       createdAt: format(addDays(now, -15), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(addDays(now, -15), "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["dinner", "anniversary", "reservation"],
//     },
//     {
//       id: "rem-008",
//       title: "Tax filing deadline",
//       description: "Submit annual tax returns",
//       dueDate: format(addDays(now, 30), "yyyy-MM-dd"),
//       dueTime: "23:59",
//       category: "Finance",
//       priority: "High",
//       reminderStatus: "Active",
//       recurring: true,
//       recurrenceType: "Yearly",
//       starred: true,
//       createdAt: format(addDays(now, -60), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(addDays(now, -5), "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["taxes", "finance", "deadline"],
//     },
//     {
//       id: "rem-009",
//       title: "Renew subscription",
//       description: "Renew streaming service subscription",
//       dueDate: format(addDays(now, 5), "yyyy-MM-dd"),
//       dueTime: "12:00",
//       category: "Personal",
//       priority: "Low",
//       reminderStatus: "Snoozed",
//       recurring: true,
//       recurrenceType: "Monthly",
//       starred: false,
//       createdAt: format(addDays(now, -25), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(addDays(now, -1), "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["subscription", "renewal", "entertainment"],
//     },
//     {
//       id: "rem-010",
//       title: "Friend's birthday",
//       description: "Buy a gift for Sarah's birthday",
//       dueDate: format(addDays(now, 3), "yyyy-MM-dd"),
//       dueTime: "09:00",
//       category: "Social",
//       priority: "Medium",
//       reminderStatus: "Active",
//       recurring: true,
//       recurrenceType: "Yearly",
//       starred: false,
//       createdAt: format(addDays(now, -40), "yyyy-MM-dd'T'HH:mm:ss"),
//       lastModified: format(addDays(now, -40), "yyyy-MM-dd'T'HH:mm:ss"),
//       tags: ["birthday", "gift", "friend"],
//     },
//   ]
// }
enum ReminderStatus {
  Active = "Active",
  Completed = "Completed",
  Snoozed = "Snoozed",
  Missed = "Missed",
}

export { ReminderStatus }


enum ReminderPriority {
  Low = "Low",
  Medium = "Medium",
  High = "High",
  Urgent = "Urgent",
}

export { ReminderPriority }

enum ReminderCategory {
  Personal = "Personal",
  Work = "Work",
  Health = "Health",
  Finance = "Finance",
  Social = "Social",
  Other = "Other",
}

export { ReminderCategory }

enum RecurrenceType {
  None = "None",
  Daily = "Daily",
  Weekly = "Weekly",
  Monthly = "Monthly",
  Yearly = "Yearly",
  Custom = "Custom",
}

export { RecurrenceType }