import ReminderPage from '@/components/ui/reminder/ReminderList'
import Head from 'next/head'
import React from 'react'

const reminder = () => {
  return (
    <div>
      <Head>
        <title>PlanPro | Reminder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/asset/planpro-favicon.svg" />
      </Head>

      <main>
        <ReminderPage />
      </main>

    </div>
  )
}

export default reminder